backend:
  name: github
  repo: ragwhoo/rutam
  branch: main
  auth_endpoint: login/oauth/authorize
  app_id: Ov23lig8AmNgTgyiiN0x

publish_mode: editorial_workflow
media_folder: "static/uploads"
public_folder: "/static/uploads"

collections:
  - name: "about"
    label: "About Section"
    format: "json"
    editor:
      preview: false
    files:
      - name: "about"
        label: "About Content"
        file: "content/about.json"
        fields:
          - { label: "Subtitle", name: "subtitle", widget: "string" }
          - { label: "Story Text", name: "storyText", widget: "markdown" }
          - { label: "About Video", name: "videoSrc", widget: "string" }

  - name: "products"
    label: "Products"
    format: "json"
    editor:
      preview: false
    files:
      - name: "products"
        label: "Product List"
        file: "content/products.json"
        fields:
          - label: "Product List"
            name: "body"
            widget: "list"
            fields:
              - { label: "Image", name: "image", widget: "image", media_folder: "", public_folder: "" }
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }

  - name: "benefits"
    label: "Health Benefits"
    format: "json"
    editor:
      preview: false
    files:
      - name: "benefits"
        label: "Benefit Cards"
        file: "content/benefits.json"
        fields:
          - label: "Benefit Cards"
            name: "body"
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }

  - name: "gallery"
    label: "Gallery Videos"
    format: "json"
    editor:
      preview: false
    files:
      - name: "gallery"
        label: "Video File Paths"
        file: "content/gallery.json"
        fields:
          - label: "Video File Paths"
            name: "body"
            widget: "list"
            field: { label: "Video Path", name: "path", widget: "string" }

  - name: "contact"
    label: "Contact Info"
    format: "json"
    editor:
      preview: false
    files:
      - name: "contact"
        label: "Contact Details"
        file: "content/contact.json"
        fields:
          - { label: "Phone", name: "phone", widget: "string" }
          - { label: "Email", name: "email", widget: "string" }
